INSERT INTO USERS VALUES ('hzarikia01', 'HZarikian01', 'ZARIKIAN', 'Hayk', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('splaza02', 'SPlaza02', 'PLAZA', 'Stephane', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('clignac03', 'CLignac03', 'LIGNAC', 'Cyril', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('pechebes04', 'PEtchebest04', 'ETCHEBEST', 'Philippe', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jcourbet05', 'JCourbet05', 'COURBET', 'Julien', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('nallagas06', 'NAllagas06', 'ALLAGAS', 'Nikos', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('dbrognia07', 'DBrogniart07', 'BROGNIART', 'Denis', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jdeep08', 'JDeep08', 'DEPP', 'Johnny', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('grush09', 'GRush09', 'RUSH', 'Geoffrey', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('kknightl10', 'KKnightley10', 'KNIGHTLEY', 'Keira', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('obloom11', 'OBloom11', 'BLOOM', 'Orlando', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jdavenpo12', 'JDavenport12', 'DAVENPORT', 'Jack', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jpryce13', 'JPryce13', 'PRYCE', 'Jonathan', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jboswall14', 'JBoswall14', 'BOSWALL', 'John', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('pwalker15', 'PWalker15', 'WALKER', 'Paul', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('vdiesel16', 'VDiesel16', 'DIESEL', 'Vin', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('mrodrige17', 'MRodriguez17', 'RODRIGUEZ', 'Michelle', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jbrewste18', 'JBrewster18', 'BREWSTER', 'Jordana', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('tcruise19', 'TCruise19', 'CRUISE', 'Tom', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jreno20', 'JReno20', 'RENO', 'Jean', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('dchamber', 'DChamberlin21', 'CHAMBERLIN', 'Donald', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('rboyce22', 'RBoyce22', 'BOYCE', 'Raymond', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('jgosling23', 'JGosling23', 'GOSLING', 'James', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('dritchie24', 'DRitchie24', 'RITCHIE', 'Dennis', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('kthompso25', 'KThompson25', 'THOMPSON', 'Kenneth', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('tlinus26', 'TLinus26', 'LINUS', 'Torvalds', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('amorte27', 'AMorte27', 'MORTE', 'Alvaro', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('ucorbero28', 'UCorbero28', 'CORBERO', 'Ursula', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('palonso29', 'PAlonso29', 'ALONSO', 'PEDRO', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('hkeuchke30', 'HKeuchkerian30', 'KEUCHKERIAN', 'Hovik', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('mpedraza31', 'MPedraza31', 'PEDRAZA', 'Maria', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('dradclif32', 'DRadcliffe32', 'RADCLIFFE', 'Daniel', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('rgrint33', 'RGrint33', 'GRINT', 'Rupert', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('ewatson34', 'EWatson34', 'WATSON', 'Emma', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('mwentwor35', 'MWentworth35', 'WENTWORTH', 'Miller', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('esnowden36', 'ESnowden36', 'SNOWDEN', 'Edward', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('swoodley37', 'QWoodley37', 'WOODLEY', 'Shailene', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('ncage38', 'NCage38', 'CAGE', 'Nicolas', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('tholland39', 'THolland39', 'HOLLAND', 'Tom', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('tmaguire40', 'TMaguire40', 'MAGUIRE', 'Tobey', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('agarfiel41', 'AGarfield41', 'GARFIELD', 'Andrew', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('cfisher42', 'CFisher42', 'FISHER', 'Carrie', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('nportman43', 'NPortman43', 'PORTMAN', 'Natalie', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('hford44', 'HFord44', 'FORD', 'Harrison', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('dridley45', 'DRidley45', 'RIDLEY', 'Daisy', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('eclarke46', 'EClarke46', 'CLARKE', 'Emilia', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('mwilliam47', 'MWilliams47', 'WILLIAMS', 'Maisie', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('kharingt48', 'KHarington48', 'HARINGTON', 'Kit', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);
INSERT INTO USERS VALUES ('caznavou49', 'CAznavour49', 'AZNAVOUR', 'Charles', 'NULL', TO_DATE('2000/01/05', 'yyyy/mm/dd'), SYSDATE);

INSERT INTO COLLECTIONS VALUES (Id_collection.nextval, 'hzarikia01', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'splaza02', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'clignac03', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'pechebes04', 'videos games');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jcourbet05', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'nallagas06', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'dbrognia07', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jdeep08', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'grush09', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'kknightl10', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'obloom11', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jdavenpo12', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jpryce13', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jboswall14', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'pwalker15', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'vdiesel16', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'mrodrige17', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jbrewste18', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'tcruise19', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jreno20', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'dchamber', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'rboyce22', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'jgosling23', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'dritchie24', 'music');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'kthompso25', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'tlinus26', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'amorte27', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'ucorbero28', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'palonso29', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'hkeuchke30', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'mpedraza31', 'music');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'dradclif32', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'rgrint33', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'ewatson34', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'mwentwor35', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'esnowden36', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'swoodley37', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'ncage38', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'tholland39', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'tmaguire40', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'agarfiel41', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'cfisher42', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'nportman43', 'videos games');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'hford44', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'dridley45', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'eclarke46', 'music');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'mwilliam47', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'kharingt48', 'book');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'caznavou49', 'Movies');
INSERT INTO COLLECTIONS VALUES (Id_collection.nextval,'hzarikia01', 'videos games');

INSERT INTO LISTS VALUES (Id_list.nextval, 1, 'Horror top', 'Horror', 'Top horreur book', 18);
INSERT INTO LISTS VALUES (Id_list.nextval, 50, 'Games top', 'Action, Adventure', 'Top games', 19);
INSERT INTO LISTS VALUES (Id_list.nextval, 2, 'Horror top', 'Horror', 'Top horreur book', 15);
INSERT INTO LISTS VALUES (Id_list.nextval, 2, 'Marvel top', 'Science fiction', 'Top Marvel book', 18);
INSERT INTO LISTS VALUES (Id_list.nextval, 4, 'Games top', 'Action, adventure', 'Top games', 14);
INSERT INTO LISTS VALUES (Id_list.nextval, 5, 'Marvel top', 'Science fiction', 'Top Marvel book', 15);
INSERT INTO LISTS VALUES (Id_list.nextval, 5, 'Horror top', 'Horror', 'Top horreur book', 19);
INSERT INTO LISTS VALUES (Id_list.nextval, 6, 'Horror top', 'Horror', 'Top horreur book', 17);
INSERT INTO LISTS VALUES (Id_list.nextval, 6, 'Resident Evil top', 'Horror', 'Top Resident Evil book', 8);
INSERT INTO LISTS VALUES (Id_list.nextval, 7, 'Horror top', 'Horror', 'Top horreur book', 11);
INSERT INTO LISTS VALUES (Id_list.nextval, 49, 'Movies top', 'All', 'Top Movies', 19);

INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'La Conspiration d''Umbrella : Resident Evil, T1', 'Stephani Danelle Perry', 'Raccoon City. Deja quatre cadavres en un mois...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Resident Evil : Des zombies et des hommes', 'Bruno Provezza', 'La Nuit des morts-vivants...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'La Mort de Gwen Stacy', 'Gerry Conway', 'Spider-Man observe par la fenetre Harry Osborn...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Spider-Man : Back in Black', 'Peter David', 'Apres qu''une balle d''assassin qui lui etait destinee...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Fatal gaming : Les enquêtes de Logicielle', 'Christian Grenier', 'Pour défier les maitres du jeu sur Internet...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Fast and Furious 9', 'Justin Lin', 'Dom Toretto mene une vie tranquille avec Letty et son fils...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Spider-Man 3', 'Sam Raimi', 'Peter Parker a enfin reussi à concilier...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Uncharted', 'Ruben Fleischer', 'Le chasseur de tresors Victor Sully...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Madagascar', 'Simon Smith', 'Alex le lion, Marty le zebre, Melman la girafe et Gloria...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Shrek', 'Andrew Adamson', 'Un ogre laid et misanthrope, Shrek, vit tranquille...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Athena', 'Romain Gavras', 'Quelques heures apres la mort tragique...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'The Batman', 'Matt Reeves', 'Dans sa deuxieme annee de lutte contre le crime...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Jurassic World : Le Monde d''apres', 'Colin Trevorrow', 'Isla Nublar et son parc ont ete detruits...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Billie Jean', 'Michael Jackson', 'Lyrics...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Smooth Criminal', 'Michael Jackson', 'Lyrics...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Fur Elise', 'Beethoven', 'Lyrics...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Not Alone', 'Aram MP3', 'Lyrics...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Ich bin Charlie', 'Maxim Noise', 'Lyrics...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Imagine', 'John Lennon', 'Lyrics...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Uncharted 3 : L''illusion de Drake', 'Naughty Dog', 'Uncharted 3 : L''Illusion de Drake est le troisieme opus de la serie de jeux video...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'God of War', 'David Jaffe', 'L''histoire de God of War se deroule au depart dans l''univers de la mythologie grecque...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Call of Duty : MW2', 'Infinity Ward', 'Call of Duty: Modern Warfare II est un jeu video de tir a la premiere personne...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Grand Theft Auto V', 'Rockstar Games', 'Grand Theft Auto V est un jeu video d''action-aventure...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Red Dead Redemption II', 'Rockstar Games', 'Red Dead Redemption II est un jeu vidÃ©o d''action-aventure en monde ouvert...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Kingdom Hearts III', 'Square Enix', 'Kingdom Hearts est une serie de jeux video d''action-RPG...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Onimusha 3 : Demon Siege', 'Capcom, Ubisoft', 'Onimusha 3: Demon Siege est un jeu video de type hack''n'' slash...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Driv3r', 'Atari Games', 'DRIV3R ou Driver 3 est un jeu video developpe par Reflections Software...');
INSERT INTO OBJECTS_REFERENCES VALUES (Id_object_reference.nextval, 'Forza Horizon 4', 'Playground Games', 'Forza Horizon 4 est un jeu video de course automobile et d''aventure...');

INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 1, 1, 20, 'I like', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 3, 1, 18, 'I like', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 2, 1, 14, 'I like', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 2, 2, 15, 'Good', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 4, 3, 15, 'Good+', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 6, 11, 19, 'Good', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 7, 11, 19, 'Good', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 8, 11, 19, 'Good', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 9, 11, 19, 'Good', 1, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 10, 11, 19, 'Good', 0, SYSDATE);
INSERT INTO OBJECTS_USERS VALUES (Id_object_user.nextval, 11, 11, 19, 'Good', 0, SYSDATE);